gText_Birch_Welcome::
	.string "Hi, there. Nice to meet you!\p"
	.string "I'm Prof. Sakura. Obviously.\p"
	.string "I just wanted to call before we\n"
	.string "meet up in Darkwing Holt tomorrow.\p"
	.string "There are some things we should\n"
	.string "get settled!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I'm sure you're familiar with Pokémon.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Here in Rika, we have a really diverse\n"
	.string "region full of all kinds of Pokémon!\p"
	.string "Trainers from all over the world travel\n"
	.string "here to catch Pokémon and challenge\l"
	.string "each other in battle!\p"
	.string "In fact, the Pokémon Trainers in Rika\n"
	.string "are the toughest around!\p"
	.string "The Pokémon League here in Rika only\n"
	.string "just started, and people are even more\l"
	.string "amped up than usual to duke it out!\p"
	.string "When I see battles, I just can't help\n"
	.string "but to record data for my research!\p"
	.string "So many Pokémon... and so very many\n"
	.string "possibilities! Oh, isn't it exciting?!\p"
	.string "...Ahem, sorry! I tend to get a little\n"
	.string "too into Pokémon sometimes.\p"
	.string "But enough about me...\p"
	.string "$"


gText_Birch_AndYouAre::
	.string "What about you?$"

gText_Birch_BoyOrGirl::
	.string "What do you look like?$"

gText_Birch_WhatsYourName::
	.string "Fantastic!\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So, it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Wonderful!\p"
	.string "{PLAYER}{KUN}, your Mom and I have been\n"
	.string "really excited about this!\p"
	.string "Your first Pokémon. It's an adventure\n"
	.string "just waiting to happen!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}, are you ready?\p"
	.string "You're about to start on a life-changing\n"
	.string "journey, my friend!\p"
	.string "Come with me, into the world of Pokémon!\n"
	.string "You'll travel, make new friends, and\l"
	.string "find new mysteries to uncover!\p"
	.string "Welcome, {PLAYER}, to a new adven-\p"
	.string ". . . . . . . . . . . . . . . . . . . .\p"
	.string "What? Yes, I know I'm almost out of\n"
	.string "data! Gah! Could you not just give me...\p"
	.string "Eheheheh, sorry, {PLAYER}! My phone\n"
	.string "is reminding me that my data plan\l"
	.string "isn't unlimited, so...\p"
	.string "I hate video calls... now, how do you...\p"
	.string "Got it! See you tomorrow!\p"
	.string "$"
